-- ============================================================
-- SHINY GMAIL AUTOMATION V2.6 LEAN — POSTGRES SCHEMA
-- ============================================================
--
-- Database:    Neon Postgres (serverless)
-- Created:     2026-05-22
-- System:      Shiny Gmail Automation V2.6 Lean
-- Workflows:   3 (Orchestrator, Email Processor Child, Telegram Rules Manager)
-- Tables:      3 (gmail_workflow_runs, gmail_message_ledger, gmail_sender_rules)
--
-- Source of Truth Model:
--   - Gmail `processed` label = operational source of truth
--   - Postgres ledger = audit / idempotency helper ONLY
--   - Postgres runs = run tracking / summary persistence
--   - Postgres rules = sender/domain classification rules
--
-- Run this script once on your Neon Postgres database.
-- All statements use IF NOT EXISTS for safe re-runs.
-- ============================================================


-- ============================================================
-- TABLE 1: gmail_workflow_runs
-- ============================================================
-- Tracks daily orchestrator execution runs.
-- One row per scheduled or manual run of Workflow A.
--
-- Used by:
--   a04 (Simple Run Guard Query)  — checks for active runs
--   a07 (Mark Run Started)        — inserts new run record
--   a23 (Mark Run Finished)       — updates run with final stats
-- ============================================================

CREATE TABLE IF NOT EXISTS gmail_workflow_runs (
    -- Primary key: UUID generated by crypto.randomUUID() in n8n
    run_id              UUID            PRIMARY KEY,

    -- Account identifier (default: 'primary')
    account             TEXT            NOT NULL,

    -- Workflow metadata
    workflow_name       TEXT,
    execution_id        TEXT,

    -- Run status
    -- Values: running, completed, completed_with_failures, failed,
    --         skipped_active_run, completed_empty_loop
    status              TEXT            NOT NULL DEFAULT 'running',

    -- Summary statistics (populated by Mark Run Finished)
    total_discovered    INTEGER         DEFAULT 0,
    total_completed     INTEGER         DEFAULT 0,
    total_failed        INTEGER         DEFAULT 0,
    total_skipped       INTEGER         DEFAULT 0,
    total_review        INTEGER         DEFAULT 0,

    -- Error details
    error_message       TEXT,

    -- Timestamps
    started_at          TIMESTAMPTZ     DEFAULT now(),
    finished_at         TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ     DEFAULT now()
);

COMMENT ON TABLE gmail_workflow_runs IS 'Tracks daily orchestrator runs for Shiny Gmail Automation V2.6 Lean.';
COMMENT ON COLUMN gmail_workflow_runs.run_id IS 'UUID primary key, generated by crypto.randomUUID() in the orchestrator.';
COMMENT ON COLUMN gmail_workflow_runs.status IS 'Run status: running, completed, completed_with_failures, failed, skipped_active_run, completed_empty_loop.';


-- ============================================================
-- TABLE 2: gmail_message_ledger
-- ============================================================
-- Audit and idempotency helper for processed emails.
-- NOT the source of truth — Gmail processed label is.
--
-- Used by:
--   b04 (Check Ledger Completed)    — checks if email was already processed
--   b14 (Upsert Ledger Completed)   — records successful processing
--   b17 (Upsert Ledger Failed)      — records failed processing
-- ============================================================

CREATE TABLE IF NOT EXISTS gmail_message_ledger (
    -- Auto-increment convenience ID
    id                  BIGSERIAL       PRIMARY KEY,

    -- Account + Gmail message ID = unique email identifier
    account             TEXT            NOT NULL,
    gmail_message_id    TEXT            NOT NULL,

    -- Email metadata (captured at processing time)
    thread_id           TEXT,
    sender              TEXT,
    subject             TEXT,

    -- Classification result
    -- Categories: unimportant, receipts, priority, email-subs, please-review
    category            TEXT,

    -- Classification source
    -- Values: ai, ai_failed, whitelist, blacklist, force_receipts, force_review,
    --         domain_whitelist, domain_blacklist, ledger, input_validation,
    --         child_error, unknown
    source              TEXT,

    -- AI confidence score (0.0 to 1.0)
    confidence          NUMERIC         DEFAULT 0,

    -- Classification reasoning (one short sentence)
    reasoning           TEXT,

    -- Processing status: completed, failed, pending
    status              TEXT            NOT NULL DEFAULT 'pending',

    -- Error details (populated on failure)
    error_message       TEXT,

    -- Timestamps
    processed_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ     DEFAULT now(),
    updated_at          TIMESTAMPTZ     DEFAULT now(),

    -- Unique constraint: one ledger entry per email per account
    CONSTRAINT uq_gmail_message_ledger_account_message
        UNIQUE (account, gmail_message_id)
);

COMMENT ON TABLE gmail_message_ledger IS 'Audit/idempotency helper for processed emails. Gmail processed label is the true source of truth.';
COMMENT ON COLUMN gmail_message_ledger.gmail_message_id IS 'Gmail API message ID (e.g., "18f1a2b3c4d5e6f7").';
COMMENT ON COLUMN gmail_message_ledger.category IS 'Classification: unimportant, receipts, priority, email-subs, please-review.';
COMMENT ON COLUMN gmail_message_ledger.source IS 'How classification was determined: ai, whitelist, blacklist, domain_whitelist, etc.';
COMMENT ON COLUMN gmail_message_ledger.status IS 'Processing status: completed (labels applied), failed (error occurred), pending (not yet processed).';


-- ============================================================
-- TABLE 3: gmail_sender_rules
-- ============================================================
-- Stores sender/domain classification rules managed via Telegram.
-- Rules are loaded by the orchestrator and applied before Gemini AI.
--
-- Used by:
--   a11 (Load Sender Rules)       — loads active rules for matching
--   c05 (List Sender Rules)       — displays rules via /rules command
--   c07 (Upsert Sender Rule)      — creates/updates rules via Telegram
--   c09 (Disable Sender Rule)     — disables rules via Telegram
-- ============================================================

CREATE TABLE IF NOT EXISTS gmail_sender_rules (
    -- Auto-increment convenience ID
    id                  BIGSERIAL       PRIMARY KEY,

    -- Account identifier
    account             TEXT            NOT NULL,

    -- Rule definition
    -- sender_pattern: email address (exact_sender) or domain name (domain)
    sender_pattern      TEXT            NOT NULL,

    -- Match type: exact_sender or domain
    -- exact_sender = full email match (e.g., "news@example.com")
    -- domain = domain + subdomain match (e.g., "example.com" matches "mail.example.com")
    match_type          TEXT            NOT NULL DEFAULT 'exact_sender',

    -- Rule type determines the category:
    --   whitelist     -> priority
    --   blacklist     -> unimportant
    --   force_receipts -> receipts
    --   force_review  -> please-review
    rule_type           TEXT            NOT NULL,

    -- Priority (lower = higher priority, default 10 for sender, 20 for domain)
    priority            INTEGER         DEFAULT 10,

    -- Whether the rule is active
    enabled             BOOLEAN         DEFAULT true,

    -- Notes (e.g., "Telegram command /whitelist")
    notes               TEXT,

    -- Timestamps
    created_at          TIMESTAMPTZ     DEFAULT now(),
    updated_at          TIMESTAMPTZ     DEFAULT now(),

    -- Unique constraint: one rule per account + pattern + match_type + rule_type
    CONSTRAINT uq_gmail_sender_rules_account_pattern_match_rule
        UNIQUE (account, sender_pattern, match_type, rule_type)
);

COMMENT ON TABLE gmail_sender_rules IS 'Sender/domain classification rules managed via Telegram for Shiny Gmail Automation V2.6 Lean.';
COMMENT ON COLUMN gmail_sender_rules.sender_pattern IS 'Email address (for exact_sender) or domain name (for domain match type).';
COMMENT ON COLUMN gmail_sender_rules.match_type IS 'exact_sender = full email match; domain = domain + subdomain match.';
COMMENT ON COLUMN gmail_sender_rules.rule_type IS 'whitelist->priority, blacklist->unimportant, force_receipts->receipts, force_review->please-review.';
COMMENT ON COLUMN gmail_sender_rules.priority IS 'Lower = higher priority. Default: 10 (sender), 20 (domain).';


-- ============================================================
-- INDEXES
-- ============================================================
-- Performance indexes for common query patterns.
-- ============================================================

-- Run guard query: find active runs for an account within 30 minutes
CREATE INDEX IF NOT EXISTS idx_workflow_runs_account_status_started
    ON gmail_workflow_runs (account, status, started_at DESC);

-- Ledger lookup: find completed entries for an account + message
-- (covered by the unique constraint, but explicit for clarity)
CREATE INDEX IF NOT EXISTS idx_message_ledger_account_message_status
    ON gmail_message_ledger (account, gmail_message_id, status);

-- Sender rules: load enabled rules for an account, ordered by priority
CREATE INDEX IF NOT EXISTS idx_sender_rules_account_enabled
    ON gmail_sender_rules (account, enabled, priority ASC);


-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================
-- Run these after schema creation to confirm everything is correct.
-- ============================================================

-- 1. Verify all three tables exist
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('gmail_workflow_runs', 'gmail_message_ledger', 'gmail_sender_rules')
ORDER BY table_name;

-- 2. Verify unique constraints exist
SELECT
    tc.constraint_name,
    tc.table_name,
    string_agg(kcu.column_name, ', ' ORDER BY kcu.ordinal_position) AS columns
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name
WHERE tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE')
  AND tc.table_schema = 'public'
  AND tc.table_name IN ('gmail_workflow_runs', 'gmail_message_ledger', 'gmail_sender_rules')
GROUP BY tc.constraint_name, tc.table_name
ORDER BY tc.table_name, tc.constraint_name;

-- 3. Verify indexes exist
SELECT
    indexname,
    tablename
FROM pg_indexes
WHERE schemaname = 'public'
  AND tablename IN ('gmail_workflow_runs', 'gmail_message_ledger', 'gmail_sender_rules')
ORDER BY tablename, indexname;

-- 4. Quick row counts (should all be 0 on fresh install)
SELECT 'gmail_workflow_runs' AS table_name, COUNT(*) AS row_count FROM gmail_workflow_runs
UNION ALL
SELECT 'gmail_message_ledger', COUNT(*) FROM gmail_message_ledger
UNION ALL
SELECT 'gmail_sender_rules', COUNT(*) FROM gmail_sender_rules;


-- ============================================================
-- SCHEMA COMPLETE
-- ============================================================
-- Shiny Gmail Automation V2.6 Lean
-- 3 tables, 3 unique constraints, 3 performance indexes
-- Ready for production use with Neon Postgres.
-- ============================================================
