-- ============================================================
-- SHINY GMAIL AUTOMATION V4.0 LEAN — POSTGRES SCHEMA
-- ============================================================
--
-- Database:    Neon Postgres (serverless)
-- Created:     2026-05-27
-- System:      Shiny Gmail Automation V4.0 Lean
-- Workflows:   3 (Orchestrator, Email Processor Child, Telegram Rules Manager)
-- Tables:      3 (gmail_workflow_runs, gmail_message_ledger, gmail_sender_rules)
--
-- Source of Truth Model:
--   - Gmail 'processed' label = operational source of truth
--   - Postgres ledger = audit / idempotency / thread-reuse helper ONLY
--   - Postgres runs = run tracking / summary persistence
--   - Postgres rules = sender/domain classification rules
--
-- Gmail Labels Required by V4.0:
--   priority
--   finances
--   accounts-subscriptions
--   account-security
--   unimportant
--   needs-review
--   processed
--
-- Fresh install only:
--   Run this script once on a fresh Neon Postgres database.
--
-- Existing V2.6 database:
--   Do NOT use this fresh schema to overwrite existing tables.
--   Use the migration script instead if you want to preserve data.
--
-- All CREATE statements use IF NOT EXISTS for safe re-runs.
-- ============================================================


-- ============================================================
-- TABLE 1: gmail_workflow_runs
-- ============================================================
-- Tracks Workflow A orchestrator execution runs.
-- One row per scheduled or manual run.
--
-- Used by V4.0 nodes:
--   Workflow A / Simple Run Guard Query
--   Workflow A / Mark Run Started
--   Workflow A / Mark Run Finished
--   Workflow A / Format Telegram Summary
-- ============================================================

CREATE TABLE IF NOT EXISTS gmail_workflow_runs (
    -- Primary key: UUID generated by crypto.randomUUID() in Workflow A
    run_id              UUID            PRIMARY KEY,

    -- Gmail account identifier; default workflow value is 'primary'
    account             TEXT            NOT NULL,

    -- Run status values used by V4.0:
    -- running, completed, completed_with_failures,
    -- completed_with_warnings, failed, timed_out
    status              TEXT            NOT NULL DEFAULT 'running',

    -- Summary statistics written by Workflow A / Mark Run Finished
    total_discovered    INTEGER         DEFAULT 0,
    completed_count     INTEGER         DEFAULT 0,
    failed_count        INTEGER         DEFAULT 0,
    review_count        INTEGER         DEFAULT 0,

    -- Failure or degraded-mode message, if any
    error_message       TEXT,

    -- Run timestamps
    started_at          TIMESTAMPTZ     DEFAULT now(),
    finished_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ     DEFAULT now(),
    updated_at          TIMESTAMPTZ     DEFAULT now()
);

COMMENT ON TABLE gmail_workflow_runs IS 'Tracks daily orchestrator runs for Shiny Gmail Automation V4.0 Lean.';
COMMENT ON COLUMN gmail_workflow_runs.run_id IS 'UUID primary key generated by Workflow A.';
COMMENT ON COLUMN gmail_workflow_runs.account IS 'Gmail account identifier, normally primary.';
COMMENT ON COLUMN gmail_workflow_runs.status IS 'running, completed, completed_with_failures, completed_with_warnings, failed, timed_out.';
COMMENT ON COLUMN gmail_workflow_runs.total_discovered IS 'Number of inbox emails discovered in the run.';
COMMENT ON COLUMN gmail_workflow_runs.completed_count IS 'Number of emails successfully classified and labeled.';
COMMENT ON COLUMN gmail_workflow_runs.failed_count IS 'Number of emails that failed processing.';
COMMENT ON COLUMN gmail_workflow_runs.review_count IS 'Number of completed emails classified as needs-review.';
COMMENT ON COLUMN gmail_workflow_runs.error_message IS 'Run-level error or warning text.';


-- ============================================================
-- TABLE 2: gmail_message_ledger
-- ============================================================
-- Audit, idempotency, and thread-reuse helper for processed emails.
-- This is NOT the operational source of truth.
-- Gmail's processed label remains the operational source of truth.
--
-- Used by V4.0 nodes:
--   Workflow B / Check Ledger Completed
--   Workflow B / Upsert Ledger Completed
--   Workflow B / Upsert Ledger Failed
--   Workflow C / Query Recent
--   Workflow C / Query Stats
--   Workflow C / Query Explain
--
-- V4.0 Categories:
--   priority
--   finances
--   accounts-subscriptions
--   account-security
--   unimportant
--   needs-review
--
-- Thread reuse:
--   A completed ledger entry in the same thread can be reused when:
--   - status = completed
--   - confidence >= 0.85
--   - updated_at is within 30 days
--   - sender domain matches
-- ============================================================

CREATE TABLE IF NOT EXISTS gmail_message_ledger (
    -- Auto-increment convenience ID
    id                  BIGSERIAL       PRIMARY KEY,

    -- Account + Gmail message ID uniquely identifies an email
    account             TEXT            NOT NULL,
    gmail_message_id    TEXT            NOT NULL,

    -- Gmail thread ID, used for same-thread reuse
    thread_id           TEXT,

    -- Normalized sender email and subject captured at processing time
    sender              TEXT,
    subject             TEXT,

    -- Classification category
    category            TEXT,

    -- Classification source / route
    -- Common values:
    --   ai
    --   ai_low_confidence
    --   ai_failed
    --   whitelist
    --   blacklist
    --   force_finance
    --   force_review
    --   thread_reuse
    --   ledger_reuse
    --   metadata_empty
    --   ledger_check_failed
    --   input_validation_failed
    --   child_execution_failed
    --   processing_failed
    source              TEXT,

    -- Confidence score, usually 0.0 to 1.0
    confidence          NUMERIC         DEFAULT 0,

    -- One-sentence classification or failure reasoning
    reasoning           TEXT,

    -- Processing status values:
    -- completed, failed, pending, invalidated
    status              TEXT            NOT NULL DEFAULT 'pending',

    -- Failure or warning message, if any
    error_message       TEXT,

    -- Ledger timestamps
    created_at          TIMESTAMPTZ     DEFAULT now(),
    updated_at          TIMESTAMPTZ     DEFAULT now(),

    -- One ledger row per Gmail message per account
    CONSTRAINT uq_gmail_message_ledger_account_message
        UNIQUE (account, gmail_message_id)
);

COMMENT ON TABLE gmail_message_ledger IS 'Audit, idempotency, and thread-reuse helper. Gmail processed label remains source of truth.';
COMMENT ON COLUMN gmail_message_ledger.gmail_message_id IS 'Gmail API message ID.';
COMMENT ON COLUMN gmail_message_ledger.thread_id IS 'Gmail thread ID used for thread reuse.';
COMMENT ON COLUMN gmail_message_ledger.sender IS 'Normalized sender email address.';
COMMENT ON COLUMN gmail_message_ledger.category IS 'priority, finances, accounts-subscriptions, account-security, unimportant, needs-review.';
COMMENT ON COLUMN gmail_message_ledger.source IS 'How classification was determined: ai, whitelist, blacklist, force_finance, force_review, thread_reuse, ledger_reuse, etc.';
COMMENT ON COLUMN gmail_message_ledger.confidence IS 'Classification confidence. Gemini classifications below 0.8 fall back to needs-review.';
COMMENT ON COLUMN gmail_message_ledger.status IS 'completed, failed, pending, invalidated.';
COMMENT ON COLUMN gmail_message_ledger.error_message IS 'Failure details or completed-with-warning details.';


-- ============================================================
-- TABLE 3: gmail_sender_rules
-- ============================================================
-- Stores sender/domain classification rules managed through Telegram.
-- Rules are loaded by Workflow A and applied before Gemini.
--
-- Used by V4.0 nodes:
--   Workflow A / Get Sender Rules
--   Workflow C / Query Rules
--   Workflow C / Upsert Rule
--   Workflow C / Disable Rule
--   Workflow C / Query Explain
--
-- Rule type mapping:
--   whitelist     -> priority
--   blacklist     -> unimportant
--   force_finance -> finances
--   force_review  -> needs-review
--
-- Match type values:
--   exact  = full sender email match
--   domain = domain and subdomain match
--
-- Rule precedence:
--   1. Lower priority value wins
--   2. At same priority, exact beats domain
--   3. Remaining ties use newest rule first
-- ============================================================

CREATE TABLE IF NOT EXISTS gmail_sender_rules (
    -- Auto-increment convenience ID
    id                  BIGSERIAL       PRIMARY KEY,

    -- Account identifier
    account             TEXT            NOT NULL,

    -- Email address for exact rules, domain for domain rules
    sender_pattern      TEXT            NOT NULL,

    -- exact or domain
    match_type          TEXT            NOT NULL DEFAULT 'exact',

    -- whitelist, blacklist, force_finance, force_review
    rule_type           TEXT            NOT NULL,

    -- Lower number = higher priority
    priority            INTEGER         DEFAULT 10,

    -- Soft delete flag; disabled rules can be listed with /rules disabled
    enabled             BOOLEAN         DEFAULT true,

    -- Rule timestamps
    created_at          TIMESTAMPTZ     DEFAULT now(),
    updated_at          TIMESTAMPTZ     DEFAULT now(),

    -- One rule per account + pattern + match type + rule type
    CONSTRAINT uq_gmail_sender_rules_rule
        UNIQUE (account, sender_pattern, match_type, rule_type)
);

COMMENT ON TABLE gmail_sender_rules IS 'Sender/domain classification rules managed via Telegram for Shiny Gmail Automation V4.0 Lean.';
COMMENT ON COLUMN gmail_sender_rules.sender_pattern IS 'Email address for exact match, or domain name for domain match.';
COMMENT ON COLUMN gmail_sender_rules.match_type IS 'exact = full email match; domain = root domain and subdomain match.';
COMMENT ON COLUMN gmail_sender_rules.rule_type IS 'whitelist -> priority, blacklist -> unimportant, force_finance -> finances, force_review -> needs-review.';
COMMENT ON COLUMN gmail_sender_rules.priority IS 'Lower = higher priority. At equal priority, exact beats domain; newest wins ties.';
COMMENT ON COLUMN gmail_sender_rules.enabled IS 'Soft-delete flag. Disabled rules are hidden by default and visible with /rules disabled.';


-- ============================================================
-- INDEXES
-- ============================================================
-- Performance indexes for common V4.0 query patterns.
-- ============================================================

-- Run guard and last-completed-run lookup
CREATE INDEX IF NOT EXISTS idx_workflow_runs_account_status_started
    ON gmail_workflow_runs (account, status, started_at DESC);

-- Exact message lookup for ledger idempotency
CREATE INDEX IF NOT EXISTS idx_message_ledger_account_message_status
    ON gmail_message_ledger (account, gmail_message_id, status);

-- Thread reuse lookup for recent completed messages in the same thread
CREATE INDEX IF NOT EXISTS idx_message_ledger_thread_reuse
    ON gmail_message_ledger (account, thread_id, status, confidence, updated_at DESC)
    WHERE thread_id IS NOT NULL AND status = 'completed';

-- Sender history for /recent sender and /explain
CREATE INDEX IF NOT EXISTS idx_message_ledger_sender
    ON gmail_message_ledger (account, sender, status, updated_at DESC)
    WHERE sender IS NOT NULL AND sender != '';

-- Active sender rules loaded by Workflow A
CREATE INDEX IF NOT EXISTS idx_sender_rules_account_enabled
    ON gmail_sender_rules (account, enabled, priority ASC);


-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================
-- Run these after schema creation to confirm everything is correct.
-- ============================================================

-- 1. Verify all three tables exist
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('gmail_workflow_runs', 'gmail_message_ledger', 'gmail_sender_rules')
ORDER BY table_name;

-- 2. Verify primary keys and unique constraints exist
SELECT
    tc.constraint_name,
    tc.table_name,
    string_agg(kcu.column_name, ', ' ORDER BY kcu.ordinal_position) AS columns
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name
WHERE tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE')
  AND tc.table_schema = 'public'
  AND tc.table_name IN ('gmail_workflow_runs', 'gmail_message_ledger', 'gmail_sender_rules')
GROUP BY tc.constraint_name, tc.table_name
ORDER BY tc.table_name, tc.constraint_name;

-- 3. Verify indexes exist
SELECT
    indexname,
    tablename
FROM pg_indexes
WHERE schemaname = 'public'
  AND tablename IN ('gmail_workflow_runs', 'gmail_message_ledger', 'gmail_sender_rules')
ORDER BY tablename, indexname;

-- 4. Quick row counts; all should be 0 on fresh install
SELECT 'gmail_workflow_runs' AS table_name, COUNT(*) AS row_count FROM gmail_workflow_runs
UNION ALL
SELECT 'gmail_message_ledger', COUNT(*) FROM gmail_message_ledger
UNION ALL
SELECT 'gmail_sender_rules', COUNT(*) FROM gmail_sender_rules;


-- ============================================================
-- SCHEMA COMPLETE
-- ============================================================
-- Shiny Gmail Automation V4.0 Lean
-- 3 tables, 3 unique constraints, 5 performance indexes
-- Ready for production use with Neon Postgres.
-- ============================================================
